/**
 * Reads SVG files from material-icon-theme and generates src/icon-data.ts.
 * Uses a deduplicated registry: unique SVGs are stored once, and
 * extension/filename maps only store the registry key (not the SVG string).
 */

import { generateManifest } from 'material-icon-theme';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const require = createRequire(import.meta.url);

const pkgPath = require.resolve('material-icon-theme/package.json');
const iconsDir = join(dirname(pkgPath), 'icons');

const manifest = generateManifest();

function readSvg(iconPath) {
  const filename = iconPath.split('/').pop();
  const fullPath = join(iconsDir, filename);
  if (!existsSync(fullPath)) return null;
  return readFileSync(fullPath, 'utf-8').trim();
}

function getIconSvgs(iconKey) {
  const def = manifest.iconDefinitions?.[iconKey];
  if (!def?.iconPath) return null;
  const dark = readSvg(def.iconPath);
  if (!dark) return null;

  const lightDef = manifest.iconDefinitions?.[iconKey + '_light'];
  const light = lightDef?.iconPath ? (readSvg(lightDef.iconPath) ?? dark) : dark;
  return { dark, light };
}

// ── Build deduplicated registry ───────────────────────────────────────────────
// registry: iconKey -> { dark, light }
const registry = {};

// extension/filename/folder -> iconKey (just the key, not the SVG)
const extKeys = {};
const nameKeys = {};
const folderKeys = {};
const folderOpenKeys = {};

/**
 * Upstream keys keep their original casing (CLAUDE.md, Caddyfile, PKGBUILD…),
 * because VS Code matches case-insensitively on its side. We do the lookup
 * ourselves against a lowercased filename, so the table has to be lowercased
 * here or those entries can never be hit.
 */
function collect(source, target) {
  for (const [rawKey, iconKey] of Object.entries(source ?? {})) {
    if (!registry[iconKey]) {
      const svgs = getIconSvgs(iconKey);
      if (svgs) registry[iconKey] = svgs;
    }
    if (registry[iconKey]) target[rawKey.toLowerCase()] = iconKey;
  }
}

collect(manifest.fileExtensions, extKeys);
collect(manifest.fileNames, nameKeys);
collect(manifest.folderNames, folderKeys);
collect(manifest.folderNamesExpanded, folderOpenKeys);

// ── Obsidian-specific extensions not in material-icon-theme ──────────────────
function addCustom(ext, iconFile, customKey) {
  if (registry[customKey]) { extKeys[ext] = customKey; return; }
  const svgPath = join(iconsDir, iconFile);
  if (!existsSync(svgPath)) return;
  const dark = readFileSync(svgPath, 'utf-8').trim();
  registry[customKey] = { dark, light: dark };
  extKeys[ext] = customKey;
}

addCustom('canvas', 'flow.svg', 'flow');
addCustom('base', 'database.svg', 'database');

// ── Default / folder icons ────────────────────────────────────────────────────
const defaultKey = manifest.file ?? 'file';
const folderKey = manifest.folder ?? 'folder';
const folderOpenKey = manifest.folderExpanded ?? 'folder-open';

if (!registry[defaultKey]) registry[defaultKey] = getIconSvgs(defaultKey) ?? { dark: '', light: '' };
if (!registry[folderKey]) registry[folderKey] = getIconSvgs(folderKey) ?? { dark: '', light: '' };
if (!registry[folderOpenKey]) registry[folderOpenKey] = getIconSvgs(folderOpenKey) ?? { dark: '', light: '' };

// ── Emit TypeScript ───────────────────────────────────────────────────────────
const output = `// Auto-generated by scripts/build-icons.mjs — do not edit manually
// Icon source: material-icon-theme (https://github.com/material-extensions/vscode-material-icon-theme)

export interface IconSet {
  dark: string;
  light: string;
}

/** Deduplicated SVG registry — each unique icon is stored exactly once */
export const iconRegistry: Record<string, IconSet> = ${JSON.stringify(registry, null, 2)};

/** Maps file extension -> iconRegistry key */
export const fileExtensionKeys: Record<string, string> = ${JSON.stringify(extKeys, null, 2)};

/** Maps exact filename -> iconRegistry key (keys are lowercase) */
export const fileNameKeys: Record<string, string> = ${JSON.stringify(nameKeys, null, 2)};

/** Maps folder name -> iconRegistry key, collapsed state (keys are lowercase) */
export const folderNameKeys: Record<string, string> = ${JSON.stringify(folderKeys, null, 2)};

/** Maps folder name -> iconRegistry key, expanded state (keys are lowercase) */
export const folderNameOpenKeys: Record<string, string> = ${JSON.stringify(folderOpenKeys, null, 2)};

export const defaultFileIconKey = ${JSON.stringify(defaultKey)};
export const folderIconKey = ${JSON.stringify(folderKey)};
export const folderOpenIconKey = ${JSON.stringify(folderOpenKey)};
`;

writeFileSync(join(rootDir, 'src/icon-data.ts'), output, 'utf-8');

// ── Keep the checked-in declaration honest ────────────────────────────────────
// icon-data.ts is gitignored, so fresh clones and Obsidian's review bot
// type-check against src/icon-data.d.ts instead. If the two drift, every value
// imported from this module silently degrades to `any`. Fail loudly instead.
const declPath = join(rootDir, 'src/icon-data.d.ts');
const declSrc = readFileSync(declPath, 'utf-8');

const namesIn = (src, constRe) =>
  new Set([
    ...[...src.matchAll(constRe)].map((m) => m[1]),
    ...[...src.matchAll(/export interface (\w+)/g)].map((m) => m[1]),
  ]);

const generatedNames = namesIn(output, /export const (\w+)/g);
const declaredNames = namesIn(declSrc, /export declare const (\w+)/g);

const undeclared = [...generatedNames].filter((n) => !declaredNames.has(n));
const stale = [...declaredNames].filter((n) => !generatedNames.has(n));

if (undeclared.length || stale.length) {
  console.error('\n❌ src/icon-data.d.ts is out of sync with the generated module.');
  if (undeclared.length) console.error(`   Generated but not declared: ${undeclared.join(', ')}`);
  if (stale.length) console.error(`   Declared but not generated: ${stale.join(', ')}`);
  console.error('   Update the declaration — it is what fresh clones type-check against.\n');
  process.exit(1);
}

const mappings =
  Object.keys(extKeys).length +
  Object.keys(nameKeys).length +
  Object.keys(folderKeys).length +
  Object.keys(folderOpenKeys).length;

console.log(
  `✅ Generated src/icon-data.ts\n` +
  `   ${Object.keys(extKeys).length} extension mappings\n` +
  `   ${Object.keys(nameKeys).length} filename mappings\n` +
  `   ${Object.keys(folderKeys).length} folder mappings (+ ${Object.keys(folderOpenKeys).length} expanded)\n` +
  `   ${Object.keys(registry).length} unique SVGs (${mappings} mappings before dedup)`
);
